Tutorial: https://courses.csail.mit.edu/6.867/wiki/images/a/a7/Qp-cvxopt.pdf

In [1]:
import numpy as np
from cvxopt import matrix

P = matrix([[0.0064,  0.0008, -0.0011, 0.0],
            [0.0008,  0.0025,     0.0, 0.0],
            [-0.0011,    0.0,  0.0004, 0.0],
            [    0.0,    0.0,     0.0, 0.0]],tc='d')

q = matrix([-0.12,-0.10,-0.07,-0.03],tc='d')

G = matrix([[1,  0,  0, 0],
            [0,  1,  0, 0],
            [0,  0,  1, 0],
            [0,  0,  0, 1]],tc='d')
h = matrix([0,0,0,0],tc='d')

A = matrix([1,1,1,1],tc='d').T
b = matrix([1],tc='d')

In [2]:
print A

[ 1.00e+00  1.00e+00  1.00e+00  1.00e+00]



In [3]:
from cvxopt import solvers

sol = solvers.qp(P,q,G,h,A,b)

     pcost       dcost       gap    pres   dres
 0: -8.4152e-02  1.7027e-01  1e+00  3e+00  8e-17
 1: -7.7105e-02  2.7242e-01  6e-02  6e-01  1e-16
 2: -8.0278e-02  2.2185e+00  9e-02  5e-01  1e-15
 3: -8.0107e-02  4.1918e+01  6e-01  5e-01  3e-14
 4: -7.9781e-02  2.8005e+03  4e+00  5e-01  1e-12
 5: -7.9730e-02  1.8144e+06  7e+01  5e-01  8e-10
 6: -7.9728e-02  4.3981e+10  2e+04  5e-01  2e-05
 7: -7.9728e-02  9.6654e+16  4e+08  5e-01  3e+01
 8: -7.9728e-02  2.1235e+25  1e+15  5e-01  1e+10
 9: -7.9728e-02  4.4170e+35  1e+24  5e-01  7e+19
10: -7.9728e-02  1.5485e+47  4e+33  5e-01  5e+31
11: -7.9728e-02  3.4118e+60  4e+46  5e-01  1e+45
12: -7.9728e-02  3.1544e+73  3e+59  5e-01  6e+57
13: -7.9728e-02  3.2583e+87  1e+72  5e-01  4e+71
14: -7.9728e-02  5.6924e+102  6e+86  5e-01  1e+87
15: -7.9728e-02  3.5518e+117  3e+101  5e-01 1e+102
16: -7.9728e-02  1.7264e+130  1e+114  5e-01 6e+114
17: -7.9728e-02  2.6468e+145  1e+129  5e-01 1e+130
18: -7.9728e-02  1.0003e+159  6e+142  5e-01 5e+143
19: -7.9728e

ValueError: domain error

In [4]:
sol

{'dual infeasibility': 4.318774907015183e-17,
 'dual objective': -22.625012490894495,
 'dual slack': 1.1823034730347304e-06,
 'gap': 1.7866380735781174e-05,
 'iterations': 3,
 'primal infeasibility': 9.06493303673679e-17,
 'primal objective': -22.624994624513757,
 'primal slack': 7.783824700687446e-08,
 'relative gap': 7.896744742835557e-07,
 's': <6x1 matrix, tc='d'>,
 'status': 'optimal',
 'x': <3x1 matrix, tc='d'>,
 'y': <0x1 matrix, tc='d'>,
 'z': <6x1 matrix, tc='d'>}

In [5]:
print np.array(sol['x'])

[[ 0.99999478]
 [ 0.50000345]
 [-0.99999992]]


In [6]:
G.T

<3x6 matrix, tc='d'>

In [7]:
np.dot(sol['x'].T,np.dot(P,sol['x'])) + np.dot(q.T,sol['x']) + 1

array([[-2.00005502]])

In [8]:
y = np.array([1,-0.2059698901171804,1])
np.dot(y.T,np.dot(np.array(P),y)) + np.dot(np.array(q).T,y) + 1

array([ 9.29284849])

In [9]:
print sol['x']

[ 1.00e+00]
[ 5.00e-01]
[-1.00e+00]

