Tutorial: https://courses.csail.mit.edu/6.867/wiki/images/a/a7/Qp-cvxopt.pdf

In [1]:
import numpy as np
from cvxopt import matrix

P = matrix([[13,12,-2],
            [12,17,6],
            [-2,6,12]],tc='d')

q = matrix([-22,-14.5,13],tc='d')

G = matrix([[1 ,  0,  0],
            [0 ,  1,  0],
            [0 ,  0,  1],
            [-1,  0,  0],
            [0 , -1,  0],
            [0 ,  0, -1]],tc='d').T

h = matrix([1,1,1,1,1,1],tc='d')

In [2]:
print h

[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]



In [3]:
from cvxopt import solvers

sol = solvers.qp(P,q,G,h)

     pcost       dcost       gap    pres   dres
 0: -2.2538e+01 -3.0261e+01  8e+00  0e+00  1e-17
 1: -2.2605e+01 -2.2734e+01  1e-01  3e-16  7e-17
 2: -2.2624e+01 -2.2626e+01  2e-03  3e-16  3e-17
 3: -2.2625e+01 -2.2625e+01  2e-05  9e-17  4e-17
Optimal solution found.


In [4]:
sol

{'dual infeasibility': 4.318774907015183e-17,
 'dual objective': -22.625012490894495,
 'dual slack': 1.1823034730347304e-06,
 'gap': 1.7866380735781174e-05,
 'iterations': 3,
 'primal infeasibility': 9.06493303673679e-17,
 'primal objective': -22.624994624513757,
 'primal slack': 7.783824700687446e-08,
 'relative gap': 7.896744742835557e-07,
 's': <6x1 matrix, tc='d'>,
 'status': 'optimal',
 'x': <3x1 matrix, tc='d'>,
 'y': <0x1 matrix, tc='d'>,
 'z': <6x1 matrix, tc='d'>}

In [5]:
print np.array(sol['x'])

[[ 0.99999478]
 [ 0.50000345]
 [-0.99999992]]


In [6]:
G.T

<3x6 matrix, tc='d'>

In [7]:
np.dot(sol['x'].T,np.dot(P,sol['x'])) + np.dot(q.T,sol['x']) + 1

array([[-2.00005502]])

In [8]:
y = np.array([1,-0.2059698901171804,1])
np.dot(y.T,np.dot(np.array(P),y)) + np.dot(np.array(q).T,y) + 1

array([ 9.29284849])

In [9]:
print sol['x']

[ 1.00e+00]
[ 5.00e-01]
[-1.00e+00]

